version: "3.7"

services:
  mongo:
  image: mongo
  container_name: database_bonaparte
  restart: always
  ports:
    - 27017:27017

  app:
    build: .
    container_name: bonaparte
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

